"""Generate app_<appid>.lua content from a game record.

Order per doc 3.4: addappid → addtoken → setManifestid → setAppTicket → setETicket → setStat
applied first to main game, then to each enabled DLC.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from opensteamtool_gui.services import steam_path as steam_path_svc
from opensteamtool_gui.utils.atomic_write import atomic_write_text

HEADER = "-- Generated by OpenSteamTool GUI. DO NOT EDIT MANUALLY."


@dataclass
class DepotEntry:
    depot_id: int
    decryption_key: str | None = None
    manifest_gid: str | None = None


@dataclass
class AppEntry:
    appid: int
    name: str = ""
    enabled: bool = True
    depots: list[DepotEntry] = field(default_factory=list)
    access_token: str | None = None
    app_ticket_hex: str | None = None
    e_ticket_hex: str | None = None
    stat_steam_id: str | None = None


@dataclass
class GameBundle:
    main: AppEntry
    dlcs: list[AppEntry] = field(default_factory=list)


def _quote(value: str) -> str:
    """Escape a Lua string literal (only " and \\ matter for our values)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _emit_block(app: AppEntry) -> list[str]:
    lines: list[str] = []
    label = app.name.strip() or "(unnamed)"
    lines.append(f"-- AppID {app.appid}: {label}")
    lines.append(f"addappid({app.appid})")
    for depot in app.depots:
        key = depot.decryption_key
        if key:
            lines.append(f'addappid({depot.depot_id}, 1, {_quote(key)})')
        else:
            lines.append(f"addappid({depot.depot_id})")
    if app.access_token:
        lines.append(f"addtoken({app.appid}, {_quote(app.access_token)})")
    for depot in app.depots:
        if depot.manifest_gid:
            lines.append(f"setManifestid({depot.depot_id}, {_quote(depot.manifest_gid)})")
    if app.app_ticket_hex:
        lines.append(f"setAppTicket({app.appid}, {_quote(app.app_ticket_hex)})")
    if app.e_ticket_hex:
        lines.append(f"setETicket({app.appid}, {_quote(app.e_ticket_hex)})")
    if app.stat_steam_id:
        lines.append(f"setStat({app.appid}, {_quote(app.stat_steam_id)})")
    return lines


def render(bundle: GameBundle, *, now: datetime | None = None) -> str:
    if now is None:
        now = datetime.now(timezone.utc)
    iso = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [HEADER, f"-- Generated at: {iso}", ""]
    lines.extend(_emit_block(bundle.main))
    for dlc in bundle.dlcs:
        if not dlc.enabled:
            continue
        lines.append("")
        lines.extend(_emit_block(dlc))
    return "\n".join(lines) + "\n"


def file_path_for(steam_path: Path, main_appid: int) -> Path:
    return steam_path_svc.lua_managed_dir(steam_path) / f"app_{main_appid}.lua"


def write(steam_path: Path, bundle: GameBundle) -> Path:
    """Render bundle and atomically write to managed/app_<appid>.lua."""
    target = file_path_for(steam_path, bundle.main.appid)
    content = render(bundle)
    atomic_write_text(target, content)
    return target


def remove(steam_path: Path, main_appid: int) -> bool:
    """Remove the managed lua file for an appid. Returns True if a file was deleted."""
    target = file_path_for(steam_path, main_appid)
    if target.exists():
        target.unlink()
        return True
    return False
