"""Unit tests for lua_generator."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from opensteamtool_gui.services.lua_generator import (
    AppEntry,
    DepotEntry,
    GameBundle,
    file_path_for,
    remove,
    render,
    write,
)


def _now() -> datetime:
    return datetime(2026, 5, 17, 12, 0, 0, tzinfo=timezone.utc)


def test_render_minimal():
    bundle = GameBundle(main=AppEntry(appid=730, name="CS2"))
    output = render(bundle, now=_now())
    assert "-- Generated by OpenSteamTool GUI" in output
    assert "addappid(730)" in output
    assert "AppID 730: CS2" in output


def test_render_with_depot_key_and_manifest():
    key = "a" * 64
    bundle = GameBundle(
        main=AppEntry(
            appid=730,
            name="CS2",
            depots=[DepotEntry(depot_id=731, decryption_key=key, manifest_gid="123456789")],
        )
    )
    output = render(bundle, now=_now())
    assert f'addappid(731, 1, "{key}")' in output
    assert 'setManifestid(731, "123456789")' in output


def test_render_emits_token_ticket_stat():
    bundle = GameBundle(
        main=AppEntry(
            appid=730,
            name="CS2",
            access_token="123",
            app_ticket_hex="deadbeef",
            e_ticket_hex="cafe",
            stat_steam_id="76561198000000000",
        )
    )
    output = render(bundle, now=_now())
    assert 'addtoken(730, "123")' in output
    assert 'setAppTicket(730, "deadbeef")' in output
    assert 'setETicket(730, "cafe")' in output
    assert 'setStat(730, "76561198000000000")' in output


def test_render_skips_disabled_dlc():
    bundle = GameBundle(
        main=AppEntry(appid=730, name="CS2"),
        dlcs=[
            AppEntry(appid=731, name="DLC1", enabled=True),
            AppEntry(appid=732, name="DLC2", enabled=False),
        ],
    )
    output = render(bundle, now=_now())
    assert "addappid(731)" in output
    assert "addappid(732)" not in output


def test_render_order_main_then_dlcs():
    bundle = GameBundle(
        main=AppEntry(appid=730, name="CS2"),
        dlcs=[AppEntry(appid=731, name="DLC", enabled=True)],
    )
    output = render(bundle, now=_now())
    main_idx = output.index("addappid(730)")
    dlc_idx = output.index("addappid(731)")
    assert main_idx < dlc_idx


def test_render_escapes_quotes_in_name():
    bundle = GameBundle(
        main=AppEntry(
            appid=730,
            name='Game "Quoted"',
            access_token="42",
        )
    )
    output = render(bundle, now=_now())
    assert 'addtoken(730, "42")' in output


def test_write_and_remove(tmp_path: Path):
    steam_path = tmp_path
    bundle = GameBundle(main=AppEntry(appid=730, name="CS2"))
    target = write(steam_path, bundle)
    assert target == file_path_for(steam_path, 730)
    assert target.is_file()
    content = target.read_text(encoding="utf-8")
    assert "addappid(730)" in content
    assert remove(steam_path, 730) is True
    assert not target.exists()
    assert remove(steam_path, 730) is False
